sim:hcal_barrel_pions:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh piplus
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh piminus

sim:hcal_barrel_kaons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh kplus
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh kminus
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh kshort
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh klong

sim:hcal_barrel_muons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_hcal/run_hcal_barrel_energy_scan.sh muon
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh muon

sim:hcal_barrel_antimuons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_hcal/run_hcal_barrel_energy_scan.sh antimuon
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh antimuon

sim:hcal_barrel_protons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_hcal/run_hcal_barrel_energy_scan.sh proton
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh proton

bench:hcal_barrel_protons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:hcal_barrel_protons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_hcal_barrel_proton.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("proton")'
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_energy_scan_analysis.cxx+("proton")'

bench:hcal_barrel_muons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:hcal_barrel_muons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_hcal_barrel_muon.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("muon")'
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_energy_scan_analysis.cxx+("muon")'

bench:hcal_barrel_antimuons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:hcal_barrel_antimuons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_hcal_barrel_antimuon.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("antimuon")'
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_energy_scan_analysis.cxx+("antimuon")'

bench:hcal_barrel_kaons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:hcal_barrel_kaons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_hcal_barrel_kplus.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("kplus")'
    - rootls -t sim_output/sim_hcal_barrel_kminus.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("kminus")'
    - rootls -t sim_output/sim_hcal_barrel_kshort.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("kshort")'
    - rootls -t sim_output/sim_hcal_barrel_klong.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("klong")'

bench:hcal_barrel_pions:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:hcal_barrel_pions"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_hcal_barrel_piplus.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("piplus")'
    - rootls -t sim_output/sim_hcal_barrel_piminus.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("piminus")'

collect_results:barrel_hcal:
  extends: .det_benchmark
  stage: collect
  needs: 
    - ["bench:hcal_barrel_muons", "bench:hcal_barrel_protons", "bench:hcal_barrel_kaons", "bench:hcal_barrel_pions"]
  script:
    - ls -lrht
    - echo " FIX ME" 

