sim:zdc:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/zdc/run_zdc_particles.sh --particle $PARTICLE
  parallel:
    matrix:
      - PARTICLE: ["neutron", "photon"]
  allow_failure: true

bench:zdc_benchmark:
  extends: .det_benchmark
  stage: benchmarks
  needs: 
    - ["sim:zdc"]
  script:
    - root -b -q benchmarks/zdc/scripts/zdc_analysis.cxx+
  parallel:
    matrix:
      - PARTICLE: ["neutron", "photon"]
  allow_failure: true

collect_results:zdc:
  extends: .det_benchmark
  stage: collect
  needs: 
    - ["bench:zdc_benchmark"]
  script:
    - ls -lrht
  allow_failure: true
