image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:$JUGGLER_TAG

default:
  artifacts:
    expire_in: 72 hours 
    paths:
      - .local/detector
      - .local/lib
      - .local/bin
      - .local/include
      - .local/share
      - results
      - config

stages:
  - config
  - initialize
  - data_init
  - simulate
  - benchmarks
  - collect
  - deploy

common:setup:
  stage: config
  script:
    - git clone https://eicweb.phy.anl.gov/EIC/benchmarks/common_bench.git setup 
    - source setup/bin/env.sh && ./setup/bin/install_common.sh

common:detector:
  stage: initialize
  needs: ["common:setup"]
  script:
    - source .local/bin/env.sh && build_detector.sh
    - mkdir -p /scratch/${CI_PROJECT_NAME}_${CI_PIPELINE_ID}
    - mkdir -p /scratch/${CI_PROJECT_NAME}_${CI_PIPELINE_ID}/sim_output
    - mkdir -p results
    - mkdir -p config
    - print_env.sh

get_data:
  stage: data_init
  needs: ["common:detector"]
  script:
    - source .local/bin/env.sh
    - ln -s "${LOCAL_DATA_PATH}/sim_output" sim_output
    - ln -s "${LOCAL_DATA_PATH}/datasets/data" data
    - cd ${LOCAL_DATA_PATH} && git clone --depth=1 https://eicweb.phy.anl.gov/EIC/datasets.git datasets

.det_benchmark:
  image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:$JUGGLER_TAG
  needs:
    - ["get_data","common:detector"]
  before_script:
    - source .local/bin/env.sh
    - ls -lrtha 
    - ln -s "${LOCAL_DATA_PATH}/sim_output" sim_output
    - ln -s "${LOCAL_DATA_PATH}/datasets/data" data
    - ls -lrtha


include: 
  - local: 'benchmarks/barrel_ecal/config.yml'
  - local: 'benchmarks/roman_pots/config.yml'
  - local: 'benchmarks/zdc/config.yml'
  - local: 'benchmarks/crystal_calorimeter/config.yml'
  - local: 'benchmarks/pid/config.yml'

deploy_results:
  stage: deploy
  needs:
    - ["collect_results:zdc","collect_results:barrel_ecal","collect_results:crystal_calorimeter"]
  script:
    - echo "deploy results!"


pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_SERVER_HOST != "eicweb.phy.anl.gov"'
  cache:
    paths:
      - node_modules/
  image: node:latest
  script:
    - mkdir public && cp doc/main.html public/index.html
  artifacts:
    paths:
      - public


