image: eicweb.phy.anl.gov:4567/containers/eic_container/eic_container:latest 

default:
  artifacts:
    paths:
      - results/
      - datasets/
      - sim_output/
      - data
        #    exclude:
        #      - .git/
        #      - datasets/.git/
  before_script:
    - git clone https://eicweb.phy.anl.gov/EIC/NPDet.git && mkdir NPDet/build
    - cd NPDet/build && cmake ../. -DCMAKE_INSTALL_PREFIX=/usr/local && make -j10 && make install
    - cd ../.. 

stages:
  - data_init
    #  - ci_gen
  - simulate
  - benchmarks
  - deploy
    #- others

get_data:
  stage: data_init
  tags:
    - sodium
  script:
    - git clone https://eicweb.phy.anl.gov/EIC/datasets.git datasets
    - ln -s datasets/data
    - mkdir -p results
    - mkdir -p sim_output

#generate_config:
#  stage: ci_gen
#  tags:
#    - sodium
#  script:
#    - ./bin/gen_ci_config -p track_test_ -i trackers > results/trackers_config.yml
#    - ./bin/gen_ci_config -p cal_test_   -i calorimeters > results/calorimeters_config.yml
#    - ./bin/gen_ci_config -p pid_test_   -i pid > results/pid_config.yml

cal_sim_1_dummy_test2:
  stage: simulate
  tags:
    - sodium
  script:
    - echo "here we run simulation"

roman_pot_simu:
  stage: simulate
  tags:
    - sodium
  script:
    - bash trackers/roman_pot_simu.sh
  allow_failure: true

cal_test_1_dummy_test2:
  stage: benchmarks
  tags:
    - sodium
  script:
    - bash calorimeters/dummy_test2.sh
  allow_failure: true

cal_test_2_dummy_test:
  stage: benchmarks
  tags:
    - sodium
  script:
    - bash calorimeters/dummy_test.sh
  allow_failure: true

cal_test_3_zdc_neutrons_reader:
  stage: benchmarks
  tags:
    - sodium
  script:
    - root -b -q calorimeters/zdc_neutrons_reader.cxx
  allow_failure: true

pid_test_1_dummy_test:
  stage: benchmarks
  tags:
    - sodium
  script:
    - bash pid/dummy_test.sh
  allow_failure: true

track_test_1_dummy_test:
  stage: benchmarks
  tags:
    - sodium
  script:
    - bash trackers/dummy_test.sh
  allow_failure: true

roman_pot_benchmark:
  stage: benchmarks
  tags:
    - sodium
  script:
    - cp NPDet/src/GenericDetectors/trackers/compact/elements.xml trackers/.
    - cp NPDet/src/GenericDetectors/trackers/compact/materials.xml trackers/.
    - root -b -q trackers/simple_tracking.cxx+
  allow_failure: true


deploy_results:
  stage: deploy
  tags:
    - sodium
  script:
    - echo "deploy results!"

      #  artifacts:
      #    paths:
      #      - datasets

      #track_test1:
      #  stage: detectors
      #  tags:
      #    - sodium
      #  script:
      #    - bash trackers/dummy_test.sh
      #  allow_failure: true
      #
      #cal_test1:
      #  stage: detectors
      #  tags:
      #    - sodium
      #  script:
      #    - bash calorimeters/dummy_test.sh
      #  allow_failure: true
      #
      #cal_test2:
      #  stage: detectors
      #  tags:
      #    - sodium
      #  script:
      #    - root -b -q calorimeters/zdc_neutrons_reader.cxx
      #  allow_failure: true


        #pid_test1:
        #  stage: detectors
        #  tags:
        #    - sodium
        #  script:
        #    - bash pid/dummy_test.sh
        #  allow_failure: true


      #pages:
      #  image: alpine
      #  when: manual
      #  stage: build
      #  script:
      #  - apk update && apk add doxygen  graphviz ttf-ubuntu-font-family
      #  - cd doc && doxygen Doxyfile && mv doxygen_output/html/ ../public/
      #  artifacts:
      #    paths:
      #    - public
      #  only:
      #  - master
