image: eicweb.phy.anl.gov:4567/containers/eic_container/eic_container:latest 

default:
  artifacts:
    paths:
      - results/
      - datasets/
      - data
        #    exclude:
        #      - .git/
        #      - datasets/.git/


stages:
  - data_init
  - benchmarks
    #  - simulate
    #- others

get_data:
  stage: data_init
  tags:
    - sodium
  script:
    - git clone https://eicweb.phy.anl.gov/EIC/datasets.git datasets
    - ln -s datasets/data
    - mkdir -p results

generate_config:
  stage: data_init
  tags:
    - sodium
  script:
    - ./bin/gen_ci_config -p track_test_ -i trackers > results/trackers_config.yml
    - ./bin/gen_ci_config -p cal_test_   -i calorimeters > results/calorimeters_config.yml
    - ./bin/gen_ci_config -p pid_test_   -i pid > results/pid_config.yml

calorimeters-pipeline:
  stage: benchmarks
  trigger:
    include:
      - artifact: results/calorimeters_config.yml
        job: generate-config

trackers-pipeline:
  stage: benchmarks
  trigger:
    include:
      - artifact: results/trackers_config.yml
        job: generate-config

pid-pipeline:
  stage: benchmarks
  trigger:
    include:
      - artifact: results/pid_config.yml
        job: generate-config

      #  artifacts:
      #    paths:
      #      - datasets

      #track_test1:
      #  stage: detectors
      #  tags:
      #    - sodium
      #  script:
      #    - bash trackers/dummy_test.sh
      #  allow_failure: true
      #
      #cal_test1:
      #  stage: detectors
      #  tags:
      #    - sodium
      #  script:
      #    - bash calorimeters/dummy_test.sh
      #  allow_failure: true
      #
      #cal_test2:
      #  stage: detectors
      #  tags:
      #    - sodium
      #  script:
      #    - root -b -q calorimeters/zdc_neutrons_reader.cxx
      #  allow_failure: true


        #pid_test1:
        #  stage: detectors
        #  tags:
        #    - sodium
        #  script:
        #    - bash pid/dummy_test.sh
        #  allow_failure: true


      #pages:
      #  image: alpine
      #  when: manual
      #  stage: build
      #  script:
      #  - apk update && apk add doxygen  graphviz ttf-ubuntu-font-family
      #  - cd doc && doxygen Doxyfile && mv doxygen_output/html/ ../public/
      #  artifacts:
      #    paths:
      #    - public
      #  only:
      #  - master
