sim:emcal_barrel_pions:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh piplus
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh piminus

sim:emcal_barrel_pi0:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh pi0

sim:emcal_barrel_electrons:
  extends: .det_benchmark
  stage: simulate
  script:
    - if [[ "$RUN_EXTENDED_BENCHMARK" == "true" ]] ; then bash benchmarks/barrel_ecal/run_emcal_barrel_energy_scan.sh electron ; fi
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh electron

sim:emcal_barrel_photons:
  extends: .det_benchmark
  stage: simulate
  script:
    - if [[ "$RUN_EXTENDED_BENCHMARK" == "true" ]] ; then bash benchmarks/barrel_ecal/run_emcal_barrel_energy_scan.sh photon ; fi
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh photon

sim:emcal_barrel_pions_electrons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_electrons.sh
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh piminus

sim:emcal_barrel_pion_rejection:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_pion_rejection.sh electron
    - bash benchmarks/barrel_ecal/run_emcal_barrel_pion_rejection.sh piminus

calib:emcal_barrel_electrons:
  extends: .det_benchmark
  stage: calibrate
  needs:
    - ["sim:emcal_barrel_electrons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_emcal_barrel_electron.root
    - root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_particles_analysis.cxx+("electron", true)'
    - mv sim_output/sim_emcal_barrel_electron.root results/.
    - echo "JSON file(s) from analysis:" ; cat results/*.json

bench:emcal_barrel_pions:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_pions"]
  script:
    - root -b -q benchmarks/barrel_ecal/scripts/emcal_barrel_pions_analysis.cxx+

bench:emcal_barrel_electrons_scan:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_electrons"]
  script:
    - if [[ "$RUN_EXTENDED_BENCHMARK" == "true" ]] ; then root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_energy_scan_analysis.cxx+("electron")' ; fi

bench:emcal_barrel_pi0:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_pi0", "calib:emcal_barrel_electrons"]
  script:
    - echo "JSON file(s) from analysis:" ; cat results/*.json
    - root -b -q benchmarks/barrel_ecal/scripts/emcal_barrel_pi0_analysis.cxx+

bench:emcal_barrel_photons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_photons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_emcal_barrel_photon.root
    - root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_particles_analysis.cxx+("photon", false)'
    - mv sim_output/sim_emcal_barrel_photon.root results/.
    - if [[ "$RUN_EXTENDED_BENCHMARK" == "true" ]] ; then root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_energy_scan_analysis.cxx+("photon")' ; fi

bench:emcal_barrel_pions_electrons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_pions_electrons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_emcal_barrel_piminus.root
    - rootls -t sim_output/sim_emcal_barrel_uniform_electrons.root
    - root -b -q benchmarks/barrel_ecal/scripts/emcal_barrel_pions_electrons_analysis.cxx+

bench:emcal_barrel_pion_rejection:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_pion_rejection"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_emcal_barrel_piRej_piminus.root
    - rootls -t sim_output/sim_emcal_barrel_piRej_electron.root
    - root -b -q benchmarks/barrel_ecal/scripts/emcal_barrel_pion_rejection_analysis.cxx+

collect_results:barrel_ecal:
  extends: .det_benchmark
  stage: collect
  needs: 
    - "calib:emcal_barrel_electrons"
    - "bench:emcal_barrel_electrons_scan"
    - "bench:emcal_barrel_photons"
    - "bench:emcal_barrel_pions"
    - "bench:emcal_barrel_pi0"
    - "bench:emcal_barrel_pions_electrons"
    - "bench:emcal_barrel_pion_rejection"
  script:
    - ls -lrht
    - echo " FIX ME" 

