sim:emcal_barrel_pions:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh piplus
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh piminus

sim:emcal_barrel_pi0:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh pi0

sim:emcal_barrel_electrons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_energy_scan.sh electron
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh electron

sim:emcal_barrel_photons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/barrel_ecal/run_emcal_barrel_energy_scan.sh photon
    - bash benchmarks/barrel_ecal/run_emcal_barrel_particles.sh photon

bench:emcal_barrel_pions:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_pions"]
  script:
    - root -b -q benchmarks/barrel_ecal/scripts/emcal_barrel_pions_analysis.cxx+

bench:emcal_barrel_pi0:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_pi0"]
  script:
    - root -b -q benchmarks/barrel_ecal/scripts/emcal_barrel_pi0_analysis.cxx+

bench:emcal_barrel_electrons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_electrons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_emcal_barrel_electron.root
    - root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_particles_analysis.cxx+("electron")'
    - root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_energy_scan_analysis.cxx+("electron")'

bench:emcal_barrel_photons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:emcal_barrel_photons"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_emcal_barrel_photon.root
    - root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_particles_analysis.cxx+("photon")'
    - root -b -q 'benchmarks/barrel_ecal/scripts/emcal_barrel_energy_scan_analysis.cxx+("photon")'

collect_results:barrel_ecal:
  extends: .det_benchmark
  stage: collect
  needs: 
    - ["bench:emcal_barrel_electrons", "bench:emcal_barrel_photons", "bench:emcal_barrel_pions", "bench:emcal_barrel_pi0"]
  script:
    - ls -lrht
    - echo " FIX ME" 

