tracking_detectors:sim_track_hits:
  extends: .det_benchmark
  stage: simulate
  script:
    - compile_analyses.py tracking_detectors
    - bash benchmarks/tracking_detectors/track_hits.sh --sim-only

tracking_detectors:plot_hits:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["tracking_detectors:sim_track_hits"]
  script:
    - bash benchmarks/tracking_detectors/track_hits.sh --analysis
