sim:roman_pot:
  stage: simulate
  extends: .det_benchmark
  script:
    - bash benchmarks/trackers/roman_pot_simu.sh

bench:roman_pot_nhits:
  stage: benchmarks
  extends: .det_benchmark
  needs:
    - ["sim:roman_pot"]
  script:
    - root -b -q benchmarks/trackers/simple_tracking.cxx+

bench:roman_pot_eta:
  stage: benchmarks
  extends: .det_benchmark
  needs:
    - ["sim:roman_pot"]
  script:
    - root -b -q benchmarks/trackers/roman_pot_hit_eta.cxx+

collect_results:roman_pot:
  extends: .det_benchmark
  stage: collect
  needs: 
    - ["bench:roman_pot_nhits","bench:roman_pot_eta"]
  script:
    - echo "Collecting results"



