#####################
# Simulations
# - Generate datasets
# - Run Geant4
# - Run Juggler
#####################

cal_sim:emcal_barrel_pions:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/calorimeters/run_emcal_barrel_pions.sh

cal_sim:emcal_barrel_electrons:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/calorimeters/run_emcal_barrel_electrons.sh

cal_sim:crystal_emcal:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/calorimeters/run_simulation_crystal.sh

cal_sim:crystal_pion:
  extends: .det_benchmark
  stage: simulate
  script:
    - npsim --runType batch --numberOfEvents 100 --compactFile ${DETECTOR_PATH}/topside.xml --inputFiles  data/emcal_electrons.hepmc  --outputFile  sim_output/output_emcal_electrons.root

cal_sim:zdc:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/calorimeters/run_simulation_zdc.sh

###################
# Benchmarks
###################

cal_bench:emcal_barrel_pions:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["cal_sim:emcal_barrel_pions"]
  script:
    - root -b -q benchmarks/calorimeters/scripts/emcal_barrel_pions_analysis.cxx+

cal_bench:emcal_barrel_electrons:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["cal_sim:emcal_barrel_electrons"]
  script:
    - rootls -t sim_output/sim_emcal_barrel_uniform_electrons.root
    - root -b -q benchmarks/calorimeters/scripts/emcal_barrel_electrons_analysis.cxx+

cal_bench:crystal_benchmark:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["cal_sim:crystal_emcal"]
  script:
    - rootls -t sim_output/output_emcal_electrons.root
    - echo " Not yet complete"
      #- root -b -q benchmarks/calorimeters/simple_checking_crystal.cxx+

    #cal_test_3_zdc_neutrons_reader:
    #stage: benchmarks
    #tags:
    #- sodium
    #script:
    #- root -b -q benchmarks/calorimeters/zdc_neutrons_reader.cxx
      #artifact:
      #  paths: 
      #    - results/
      #allow_failure: true

cal_bench:zdc_benchmark:
  extends: .det_benchmark
  stage: benchmarks
  needs: 
    - ["cal_sim:zdc"]
  script:
    - echo " Not yet complete"
    #- root -b -q benchmarks/calorimeters/simple_checking.cxx+

cal_bench:zdc_benchmark_info_histogram:
  extends: .det_benchmark
  stage: benchmarks
  needs: 
    - ["cal_sim:zdc"]
  script:
    - root -b -q benchmarks/calorimeters/simple_info_plot_histograms.cxx+

