variables:
  ETAMIN: "-4.5"
  ETAMAX: "+4.5"
  ETASTEP: "0.01"
  PHIMIN: "0.0"
  PHIMAX: "6.28318530718"
  PHISTEP: "0.01"
  TRACKING_RHOMAX: "103."
  TRACKING_ZNMAX: "191."
  TRACKING_ZPMAX: "350."
  ECAL_RHOMAX: "230."
  ECAL_ZNMAX: "355."
  ECAL_ZPMAX: "380."

bench:materialScanEta:
  stage: benchmarks
  extends: .det_benchmark
  script:
    - echo ".x benchmarks/others/materialScanEta.cxx($ETAMIN, $ETAMAX, $ETASTEP, $PHIMIN)" | materialScan ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml -interactive
    - mkdir results/images/
    - mv materialScanEta.png results/images/materialScanEta.png
    - mv materialScanEta.pdf results/images/materialScanEta.pdf

bench:materialScanEta:tracking:
  stage: benchmarks
  extends: .det_benchmark
  script:
    - echo ".x benchmarks/others/materialScanEta.cxx($ETAMIN, $ETAMAX, $ETASTEP, $PHIMIN, $TRACKING_RHOMAX, $TRACKING_ZNMAX, $TRACKING_ZPMAX)" | materialScan ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml -interactive
    - mkdir results/images/
    - mv materialScanEta.png results/images/materialScanEtaTracking.png
    - mv materialScanEta.pdf results/images/materialScanEtaTracking.pdf

bench:materialScanEta:ecal:
  stage: benchmarks
  extends: .det_benchmark
  script:
    - echo ".x benchmarks/others/materialScanEta.cxx($ETAMIN, $ETAMAX, $ETASTEP, $PHIMIN, $ECAL_RHOMAX, $ECAL_ZNMAX, $ECAL_ZPMAX)" | materialScan ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml -interactive
    - mkdir results/images/
    - mv materialScanEta.png results/images/materialScanEtaEcal.png
    - mv materialScanEta.pdf results/images/materialScanEtaEcal.pdf

bench:materialScanEtaPhi:
  stage: benchmarks
  extends: .det_benchmark
  script:
    - echo ".x benchmarks/others/materialScanEtaPhi.cxx($ETAMIN, $ETAMAX, $ETASTEP, $PHIMIN, $PHIMAX, $PHISTEP)" | materialScan ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml -interactive
    - mkdir results/images/
    - mv materialScanEtaPhi.png results/images/materialScanEtaPhi.png
    - mv materialScanEtaPhi.pdf results/images/materialScanEtaPhi.pdf

bench:materialScanEtaPhi:tracking:
  stage: benchmarks
  extends: .det_benchmark
  script:
    - echo ".x benchmarks/others/materialScanEtaPhi.cxx($ETAMIN, $ETAMAX, $ETASTEP, $PHIMIN, $PHIMAX, $PHISTEP, $TRACKING_RHOMAX, $TRACKING_ZNMAX, $TRACKING_ZPMAX)" | materialScan ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml -interactive
    - mkdir results/images/
    - mv materialScanEtaPhi.png results/images/materialScanEtaPhiTracking.png
    - mv materialScanEtaPhi.pdf results/images/materialScanEtaPhiTracking.pdf

bench:materialScanEtaPhi:ecal:
  stage: benchmarks
  extends: .det_benchmark
  script:
    - echo ".x benchmarks/others/materialScanEtaPhi.cxx($ETAMIN, $ETAMAX, $ETASTEP, $PHIMIN, $PHIMAX, $PHISTEP, $ECAL_RHOMAX, $ECAL_ZNMAX, $ECAL_ZPMAX)" | materialScan ${DETECTOR_PATH}/${DETECTOR_CONFIG}.xml -interactive
    - mkdir results/images/
    - mv materialScanEtaPhi.png results/images/materialScanEtaPhiEcal.png
    - mv materialScanEtaPhi.pdf results/images/materialScanEtaPhiEcal.pdf

collect_results:materialscan:
  extends: .det_benchmark
  stage: collect
  needs:
    - ["bench:materialScanEta", "bench:materialScanEta:tracking", "bench:materialScanEta:ecal", "bench:materialScanEtaPhi", "bench:materialScanEtaPhi:tracking", "bench:materialScanEtaPhi:ecal"]
  script:
    - ls -lrht
