sim:backward:
  extends: .det_benchmark
  stage: simulate
  script:
    - npsim --runType batch --numberOfEvents 100 --compactFile ${DETECTOR_PATH}/${JUGGLER_DETECTOR}.xml --enableGun --gun.energy "5*GeV" --gun.particle "${PARTICLE}" --gun.thetaMin 130*deg --gun.thetaMax 177*deg --gun.distribution "cos(theta)" --outputFile sim_output/sim_pid_backward_${PARTICLE}_5GeV.root
    - rootls -t sim_output/sim_pid_backward_${PARTICLE}_5GeV.root
  parallel:
    matrix:
      - PARTICLE: ["e-", "pi+", "proton"]

bench:mrich:
  extends: .det_benchmark
  stage: benchmarks
  needs: ["sim:backward"]
  script:
    - |
      if [[ ${JUGGLER_DETECTOR_VERSION} =~ acadia ]]; then
        echo "Performing MRICH benchmarks for acadia"
        mkdir -p results/pid/backward/mrich/
        root -t -x -q -b "benchmarks/pid/scripts/mrich_analysis.cxx+(\"sim_output/sim_pid_backward_${PARTICLE}_5GeV.root\", \"${PARTICLE}\")"
      else
        echo "Skipping MRICH Benchmarks for non-acadia detector version ${JUGGLER_DETECTOR_VERSION}"
      fi
  parallel:
    matrix:
      - PARTICLE: ["e-", "pi+", "proton"]

bench:erich:
  extends: .det_benchmark
  stage: benchmarks
  needs: ["sim:backward"]
  script:
    - |
      if [[ ${JUGGLER_DETECTOR_VERSION} =~ acadia ]]; then
        echo "Skipping ERICH benchmarks for acadia"
      else
        echo "Doing MRICH Benchmarks for ${JUGGLER_DETECTOR_VERSION}"
        echo "FIXME: needs implementing"
      fi
  parallel:
    matrix:
      - PARTICLE: ["e-", "pi+", "proton"]

collect_results:pid:
  extends: .det_benchmark
  stage: collect
  #needs: 
  script:
    - ls -lrht

