#stages:
#  #- simulate
#  - benchmarks
cal_test_1_dummy_test2:
  stage: benchmarks
  script:
    - bash calorimeters/dummy_test2.sh
  artifact:
    paths: 
      - results/
  allow_failure: true

cal_test_2_dummy_test:
  stage: benchmarks
  script:
    - bash calorimeters/dummy_test.sh
  artifact:
    paths: 
      - results/
  allow_failure: true

cal_test_3_zdc_neutrons_reader:
  stage: benchmarks
  script:
    - root -b -q calorimeters/zdc_neutrons_reader.cxx
  artifact:
    paths: 
      - results/
  allow_failure: true

