image: eicweb.phy.anl.gov:4567/containers/eic_container/eic_container:latest 

default:
  artifacts:
    paths:
      - results/
      - datasets/
      - data
stages:
  - simulate
  - benchmarks

cal_sim_1_dummy_test2:
  stage: benchmarks
  tags:
    - sodium
  script:
    - echo "here we run simulation"
      #artifact:
      #  paths: 
      #    - results/
  allow_failure: true

cal_test_1_dummy_test2:
  stage: benchmarks
  tags:
    - sodium
  script:
    - bash calorimeters/dummy_test2.sh
      #artifact:
      #  paths: 
      #    - results/
  allow_failure: true

cal_test_2_dummy_test:
  stage: benchmarks
  tags:
    - sodium
  script:
    - bash calorimeters/dummy_test.sh
      #artifact:
      #  paths: 
      #    - results/
  allow_failure: true

cal_test_3_zdc_neutrons_reader:
  stage: benchmarks
  tags:
    - sodium
  script:
    - root -b -q calorimeters/zdc_neutrons_reader.cxx
      #artifact:
      #  paths: 
      #    - results/
  allow_failure: true

